// -----------------------------------------------------------------------------
// DECIDR AI — Core domain types
// These types are shared across services, API routes and UI components so the
// whole app agrees on a single shape for requirements, products and results.
// -----------------------------------------------------------------------------

export type Currency = "GBP" | "USD" | "EUR";

export type ProductCategory =
  | "laptops"
  | "headphones"
  | "smartphones"
  | "monitors"
  | "cameras"
  | "running-shoes"
  | "office-chairs"
  | "coffee-machines"
  | "robot-vacuums"
  | "air-purifiers";

export type Availability = "in_stock" | "low_stock" | "out_of_stock" | "preorder";

/** A single factual product record. Never generated by the LLM — always sourced
 * from the product database / product data provider. */
export interface Product {
  id: string;
  title: string;
  brand: string;
  category: ProductCategory;
  subcategory: string;
  price: number;
  currency: Currency;
  rating: number; // 0-5
  reviewCount: number;
  image: string;
  description: string;
  specifications: Record<string, string>;
  features: string[];
  availability: Availability;
  merchantId: string;
  productUrl: string;
  affiliateUrl: string;
  createdAt: string;
  updatedAt: string;
}

export interface Merchant {
  id: string;
  name: string;
  domain: string;
  logo?: string;
  status: "active" | "paused";
}

// -----------------------------------------------------------------------------
// Requirements — the structured object the whole recommendation pipeline runs on
// -----------------------------------------------------------------------------

export type Priority = "essential" | "important" | "nice_to_have";

export type PortabilityPreference = "performance" | "balanced" | "lightweight";
export type PerformancePreference = "performance" | "balanced" | "efficiency";
export type ValuePreference = "premium" | "balanced" | "budget";

export interface PriorityWeighting {
  key: string; // e.g. "battery_life", "weight", "noise_cancellation"
  label: string;
  priority: Priority;
}

export interface StructuredRequirement {
  id: string;
  sessionId: string;
  category: ProductCategory | null;
  subcategory?: string;
  budgetMin?: number;
  budgetMax?: number;
  currency: Currency;
  useCases: string[];
  mustHaveFeatures: string[];
  preferredFeatures: string[];
  excludedFeatures: string[];
  priorities: PriorityWeighting[];
  constraints: string[];
  brandPreferences: string[];
  brandExclusions: string[];
  portabilityPreference?: PortabilityPreference;
  performancePreference?: PerformancePreference;
  valuePreference?: ValuePreference;
  rawInput: string;
  confidence: number; // 0-1, how confident extraction was
  missingFields: string[]; // drives clarification question generation
  createdAt: string;
  updatedAt: string;
}

// -----------------------------------------------------------------------------
// Clarification
// -----------------------------------------------------------------------------

export interface ClarificationOption {
  value: string;
  label: string;
}

export interface ClarificationQuestion {
  id: string;
  requirementField: string; // which field on StructuredRequirement this resolves
  question: string;
  type: "single_select" | "multi_select" | "text";
  options?: ClarificationOption[];
}

export interface ClarificationAnswer {
  questionId: string;
  requirementField: string;
  value: string | string[];
}

// -----------------------------------------------------------------------------
// Recommendation scoring
// -----------------------------------------------------------------------------

export interface ScoreBreakdown {
  budgetFit: number;
  categoryFit: number;
  useCaseFit: number;
  requiredFeatures: number;
  preferences: number;
  performance: number;
  portability: number;
  value: number;
  rating: number;
  availability: number;
}

export interface ScoredProduct {
  product: Product;
  overallScore: number; // 0-100
  scoreBreakdown: ScoreBreakdown;
  matchedRequirements: string[];
  tradeoffs: string[];
  warnings: string[];
  reasons: string[];
  badge?: "best_overall" | "best_value" | "best_performance";
}

export interface RecommendationResult {
  id: string;
  sessionId: string;
  requirementId: string;
  items: ScoredProduct[];
  generatedAt: string;
  explanationSource: "ai" | "deterministic_fallback";
}

// -----------------------------------------------------------------------------
// Sessions, saved recommendations, lists
// -----------------------------------------------------------------------------

export type SessionStatus = "in_progress" | "clarifying" | "completed" | "abandoned";

export interface DiscoverySession {
  id: string;
  userId: string | null;
  status: SessionStatus;
  rawInput: string;
  requirement?: StructuredRequirement;
  questions: ClarificationQuestion[];
  answers: ClarificationAnswer[];
  result?: RecommendationResult;
  createdAt: string;
  updatedAt: string;
}

export interface SavedRecommendation {
  id: string;
  userId: string;
  sessionId: string;
  name: string;
  category: ProductCategory | null;
  productIds: string[];
  status: "saved" | "purchased" | "archived";
  notes?: string;
  createdAt: string;
}

export interface ShoppingList {
  id: string;
  userId: string;
  name: string;
  budget?: number;
  currency: Currency;
  items: ShoppingListItem[];
  createdAt: string;
  updatedAt: string;
}

export interface ShoppingListItem {
  id: string;
  productId: string;
  position: number;
  addedAt: string;
}

// -----------------------------------------------------------------------------
// Merchant tracking
// -----------------------------------------------------------------------------

export interface MerchantClickEvent {
  id: string;
  userId: string | null;
  sessionId: string;
  recommendationId?: string;
  productId: string;
  merchantId: string;
  timestamp: string;
  source: "recommendation_card" | "product_detail" | "comparison" | "list";
}

// -----------------------------------------------------------------------------
// Analytics
// -----------------------------------------------------------------------------

export type AnalyticsEventName =
  | "page_viewed"
  | "session_started"
  | "requirement_submitted"
  | "requirements_extracted"
  | "clarification_started"
  | "clarification_answered"
  | "recommendation_generated"
  | "product_viewed"
  | "comparison_started"
  | "recommendation_saved"
  | "recommendation_unsaved"
  | "list_created"
  | "product_added_to_list"
  | "product_removed_from_list"
  | "account_created"
  | "merchant_clicked"
  | "ai_request_started"
  | "ai_request_completed"
  | "ai_request_failed";

export interface AnalyticsEvent {
  id: string;
  userId: string | null;
  sessionId?: string;
  name: AnalyticsEventName;
  properties: Record<string, unknown>;
  timestamp: string;
}

// -----------------------------------------------------------------------------
// AI usage tracking
// -----------------------------------------------------------------------------

export type AIFeature =
  | "requirement_extraction"
  | "clarification_generation"
  | "recommendation_explanation"
  | "list_optimization";

export interface AIUsageRecord {
  id: string;
  feature: AIFeature;
  provider: "openai" | "deterministic_fallback";
  model?: string;
  success: boolean;
  estimatedTokens: number;
  estimatedCostUsd: number;
  latencyMs: number;
  errorMessage?: string;
  timestamp: string;
}

// -----------------------------------------------------------------------------
// User preferences
// -----------------------------------------------------------------------------

export interface UserPreferences {
  userId: string;
  preferredCurrency: Currency;
  brandAffinities: string[];
  pricePreference: ValuePreference;
  notifyOnPriceDrops: boolean;
  updatedAt: string;
}

export interface Profile {
  id: string;
  email: string;
  fullName?: string;
  createdAt: string;
  isAdmin: boolean;
}
